//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.ItemProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ItemProxy.IItemService")]
    public interface IItemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/GetAll", ReplyAction="http://tempuri.org/IItemService/GetAllResponse")]
        System.Collections.Generic.List<Models.Item> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/GetAll", ReplyAction="http://tempuri.org/IItemService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Models.Item>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/Delete", ReplyAction="http://tempuri.org/IItemService/DeleteResponse")]
        bool Delete(Models.Item item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/Delete", ReplyAction="http://tempuri.org/IItemService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(Models.Item item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/SaveOrUpdate", ReplyAction="http://tempuri.org/IItemService/SaveOrUpdateResponse")]
        bool SaveOrUpdate(Models.Item item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/SaveOrUpdate", ReplyAction="http://tempuri.org/IItemService/SaveOrUpdateResponse")]
        System.Threading.Tasks.Task<bool> SaveOrUpdateAsync(Models.Item item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/GetRatedItemsByCategory", ReplyAction="http://tempuri.org/IItemService/GetRatedItemsByCategoryResponse")]
        System.Collections.Generic.List<Models.RatedItem> GetRatedItemsByCategory(Models.Category cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/GetRatedItemsByCategory", ReplyAction="http://tempuri.org/IItemService/GetRatedItemsByCategoryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Models.RatedItem>> GetRatedItemsByCategoryAsync(Models.Category cat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IItemServiceChannel : Test.ItemProxy.IItemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemServiceClient : System.ServiceModel.ClientBase<Test.ItemProxy.IItemService>, Test.ItemProxy.IItemService {
        
        public ItemServiceClient() {
        }
        
        public ItemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Models.Item> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Models.Item>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public bool Delete(Models.Item item) {
            return base.Channel.Delete(item);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(Models.Item item) {
            return base.Channel.DeleteAsync(item);
        }
        
        public bool SaveOrUpdate(Models.Item item) {
            return base.Channel.SaveOrUpdate(item);
        }
        
        public System.Threading.Tasks.Task<bool> SaveOrUpdateAsync(Models.Item item) {
            return base.Channel.SaveOrUpdateAsync(item);
        }
        
        public System.Collections.Generic.List<Models.RatedItem> GetRatedItemsByCategory(Models.Category cat) {
            return base.Channel.GetRatedItemsByCategory(cat);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Models.RatedItem>> GetRatedItemsByCategoryAsync(Models.Category cat) {
            return base.Channel.GetRatedItemsByCategoryAsync(cat);
        }
    }
}
