//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.RatingProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RatingProxy.IRatingService")]
    public interface IRatingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRatingService/DeleteRating", ReplyAction="http://tempuri.org/IRatingService/DeleteRatingResponse")]
        bool DeleteRating(Models.Rating rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRatingService/DeleteRating", ReplyAction="http://tempuri.org/IRatingService/DeleteRatingResponse")]
        System.Threading.Tasks.Task<bool> DeleteRatingAsync(Models.Rating rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRatingService/AddRating", ReplyAction="http://tempuri.org/IRatingService/AddRatingResponse")]
        bool AddRating(Models.Rating rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRatingService/AddRating", ReplyAction="http://tempuri.org/IRatingService/AddRatingResponse")]
        System.Threading.Tasks.Task<bool> AddRatingAsync(Models.Rating rating);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRatingServiceChannel : Test.RatingProxy.IRatingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RatingServiceClient : System.ServiceModel.ClientBase<Test.RatingProxy.IRatingService>, Test.RatingProxy.IRatingService {
        
        public RatingServiceClient() {
        }
        
        public RatingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RatingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RatingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RatingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool DeleteRating(Models.Rating rating) {
            return base.Channel.DeleteRating(rating);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteRatingAsync(Models.Rating rating) {
            return base.Channel.DeleteRatingAsync(rating);
        }
        
        public bool AddRating(Models.Rating rating) {
            return base.Channel.AddRating(rating);
        }
        
        public System.Threading.Tasks.Task<bool> AddRatingAsync(Models.Rating rating) {
            return base.Channel.AddRatingAsync(rating);
        }
    }
}
